### ISSUE TITLE
[Feature Request] show server name as command response

### ISSUE THREAD

**Issue by Lorias-Jak** [kennytv/Maintenance#100]
I have maintenance running on my velocity proxy. If i turn the maintenance mode on for a specific server (with starttimer / endtimer or schedule) i cannot see if it worked or it turned on for the whole network. 

It would be cool if the %SERVER% param is also available in the lang file when the plugin is running threw a proxy

**Comment by kennytv** [comment]
https://github.com/kennytv/Maintenance/commit/b71e1ce25d77a3726f5183d6b4b33ec800bf5df6
