### ISSUE TITLE
is:issue is:open [Sponge Forge 1.16.5] 

### ISSUE THREAD

**Issue by DreamDuster** [kennytv/Maintenance#101]
## Bug reproducibility
So I'm using Maintenace Version: 4.0.1, and it keeps telling me to update to Version 4.1.0 for Sponge Forge, when clearly on the plugin's list of sponge forge has no Version 4.1.0

## Error
**[Is there an error? Save it via https://pastebin.com/ and link paste the link.](https://ore.spongepowered.org/KennyTV/Maintenance/versions)**

## Server information
**Just gives me a chat message to update to version 4.1.0 when clearly there's no option for Sponge Forge for this updated version**

**Comment by kennytv** [comment]
I'm no longer updating Maintenance on the Sponge forums/Ore, downloads have been moved to https://modrinth.com/plugin/maintenance
