### ISSUE TITLE
messages are duplicated on velocity

### ISSUE THREAD

**Issue by 7n7e7o7** [kennytv/Maintenance#129]
## Bug reproducibility
**How does the problem occur/what are the steps to reproduce it?**
Entered /maintenance on 

## Error
**Is there an error? Save it via https://pastebin.com/ and link paste the link.**
No error

## Server information
**Type '/maintenance dump' and paste the given link here**

**Comment by 7n7e7o7** [comment]
![messagedouble](https://github.com/user-attachments/assets/90e2dad8-269d-4f3c-9c3b-b653a8e873eb)

**Comment by kennytv** [comment]
That'd be a console specific bug I think, since the broadcast also includes the console, + feedback from you running the command
