### ISSUE TITLE
This plugin does not work

### ISSUE THREAD

**Issue by xkuyax** [KennyTV/Maintenance#13]
## Issue
Include here how the problem occured and how it's reproduceable.
If present, also paste the entire error message from the console, preferably via a https://hastebin.com/ link.

## Necessary server information
**Running on**: <BungeeCord/Bukkit>

**Maintenance version**: <>

## Other information
**Other motd changing plugins**: <>

**ProtocolLib version**: <>

shit does not work 0/5 STARS

NEXT

**Comment by KennyTV** [comment]
0/10 zu wenig Alkohol
