### ISSUE TITLE
Errors when players try to join, errors running maintence dump

### ISSUE THREAD

**Issue by CodingWithAnxiety** [kennytv/Maintenance#132]
## Bug reproducibility
**How does the problem occur/what are the steps to reproduce it?**
Player joins my server with maintenance mode off

## Error
**Is there an error? Save it via https://pastebin.com/ and link paste the link.**
https://mclo.gs/RzJKBcE

## Server information
**Type '/maintenance dump' and paste the given link here**
Somehow, running this command produced a _second_ error.

https://mclo.gs/d1qwflj

I've been running into **constant** errors with maintenance lately.

**Comment by kennytv** [comment]
Your config is broken, at the very least it's missing the `fallback` field

**Comment by CodingWithAnxiety** [comment]
> Your config is broken, at the very least it's missing the `fallback` field

I have the fallback field empty since I want it to kick people when It urn the mode on.

**Comment by kennytv** [comment]
What does your config look like there? The only valid values are `""` or `[]`

**Comment by kennytv** [comment]
In any case, missing fallback fields/values are also handled now since this isn't the first time someone ran into it https://github.com/kennytv/Maintenance/commit/72b5f38e634ac516145f2de3430d044a317b72bb

**Comment by CodingWithAnxiety** [comment]
> In any case, missing fallback fields/values are also handled now since this isn't the first time someone ran into it [72b5f38](https://github.com/kennytv/Maintenance/commit/72b5f38e634ac516145f2de3430d044a317b72bb). You can download dev builds from the actions tab (dumps are also fixed)

Thank you. <3
