### ISSUE TITLE
[Suggestion] Allow using absolute timer values

### ISSUE THREAD

**Issue by xllifi** [kennytv/Maintenance#134]
"Absolute timer values" means UNIX timestamps.

Current steps to start maintenance at set date:
1. Get target UNIX timestamp and current UNIX timestamp
2. Subtract target from current
3. Divide by 60 and round up
4. Create a timer (that will still be approximate!!!)

Steps with this feature:
1. Get target UNIX timestamp
2. Create a timer (that will be actually precise)

**Comment by kennytv** [comment]
It'll accept time durations, including `1231237s` etc. in seconds now, that's the best I can offer for now
