### ISSUE TITLE
Showing players names in Version where MAINTENANCE stated

### ISSUE THREAD

**Issue by PSYCHEER** [kennytv/Maintenance#137]
## Bug reproducibility
Play on server and check server list from another client, hover over version of server and playerlist comes out

## Error
NO

## Server information
![{CD8D8378-893C-4DD3-8088-3037107F5543}](https://github.com/user-attachments/assets/96e191bb-5243-49c6-8685-bbdae3c52e15)
![image](https://github.com/user-attachments/assets/80154a3d-c63c-40f6-8ca2-2f8270f7c6d3)

Maintenance 4.2.1 Velocity only
Velocity velocity-3.3.0-SNAPSHOT-431
Backend servers 1.21.1-2304-dee41bc

**Comment by kennytv** [comment]
Fixed in https://github.com/kennytv/Maintenance/commit/3b9ef8b006dba73583b8d64bb93aba1a52a72270
