### ISSUE TITLE
Plugin not working in Velocity 1.21.1

### ISSUE THREAD

**Issue by Safi-STE** [kennytv/Maintenance#140]
/maintenance doesn't work in-game. I am using a Velocity server. When I join my lobby, I do /maintenance and nothing happend. I even tried /mt. But it would just show in red and say "Unknown or incomplete command". I have OP on my servers. I don't understand what's happening. Do I need to download the plugin on each backend server? I used the Velocity version of the plugin from Modrinth.

**Comment by kennytv** [comment]
You need permissions on the proxy through a permission plugin like luckperms

**Comment by Safi-STE** [comment]
I do have Luckperms and it's connected through a MySQL Database. How do I give permission?
