### ISSUE TITLE
Commands broken

### ISSUE THREAD

**Issue by TheCoolOne123** [KennyTV/Maintenance#30]
## Bug reproducibility
Latest version of Velocity and the plugin!
Do any command in console -> Server crashes
Do any command ingame -> Get kicked

## Error
https://pastebin.com/KA2HCSUJ

## Server information
**Type '/maintenance dump' and paste the given link here**
Can't server crashed on the spot

**Comment by KennyTV** [comment]
Either use the latest dev build (https://kennytv.eu/maintenance/snapshot) or wait for the 3.0.2 release tomorrow (I'll close the issue as soon as I fully released it)

**Comment by TheCoolOne123** [comment]
No problem!
We've started using bungee and someone recommended using this!
