### ISSUE TITLE
Custom MOTD crash

### ISSUE THREAD

**Issue by zExtrem57** [KennyTV/Maintenance#37]
## Bug reproducibility
**How does the problem occur/what are the steps to reproduce it?**
Setting a custom MOTD for timer or non-timer maintenance causes the plugin to hang-up on Bungee after some minutes

## Error
**Is there an error? Save it via https://pastebin.com/ and link paste the link.**
https://pastebin.com/VR3y6er5

## Server information
**Type '/maintenance dump' and paste the given link here**
Can't do it :/

**Comment by KennyTV** [comment]
Thanks for reporting it, fixed with the lastest commit - if you want it, either build it from the dev branch yourself or download it from a channel in the discord server!
