### ISSUE TITLE
[Feature request] kickmessage per server, while using bungee

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [KennyTV/Maintenance#38]
It would be wonderful if we could set kickmessage per server, while using plugin on bungee. Then we could set unique informations about maintenance on each server and we won't be limited to changing lang each time and having maintenance only on one server.

It could be setted by command or in config - default kickmessage will be this one from lang, but if the specified would be set - it would be used

**Comment by KennyTV** [comment]
Thank you for your suggestion, you can see info on the 2 new fields here https://github.com/KennyTV/Maintenance/wiki/Configuration#language-file

You can join the Discord, build the project yourself, or wait for the full 3.0.5 release to use it :)
