### ISSUE TITLE
Multiple Ping Messages

### ISSUE THREAD

**Issue by rowan-smith** [KennyTV/Maintenance#4]
I couldn't find a feature or suggestions area anywhere so, I created one. Sorry <3

## Feature
Possibly add support for multiple ping messages?
pingmessage:
    - "Ping Message 1%newline%Maintenance"
    - "Ping Message 2%newline%Maintenance"

## Why?
Well, I came to this scenario when I was looking to add a quirky set of messages. Like you would on another plugin like ServerListPlus, where is just chooses the messages randomly.

**Comment by KennyTV** [comment]
Yeah, sounds nice. I might have to remove the setmotd command for a while, but I can make multiple motds for the 2.3 release.
