### ISSUE TITLE
Maintenance Player did'n send it to Emergency Hub

### ISSUE THREAD

**Issue by Norge100** [KennyTV/Maintenance#41]
## Bug reproducibility
**How does the problem occur/what are the steps to reproduce it?**
The player will connect the Hub if maintenance is on and change config waiting-server
## Error
**Is there an error? Save it via https://pastebin.com/ and link paste the link.**
Nop
## Server information
**Type '/maintenance dump' and paste the given link here**
https://hasteb.in/fejavowi

**Comment by KennyTV** [comment]
So you enabled maintenance globally (`/maintenance on`) and the player did not get send to your waiting server? if so, can you also paste the content of your config please?

**Comment by Norge100** [comment]
https://hasteb.in/manetelo.yaml

**Comment by KennyTV** [comment]
Do you actually have a server called "EmergencyHub" registered in your Bungee that is accessible to players (without special permissions)?

**Comment by Norge100** [comment]
Yes. And it don't need special permissions

**Comment by KennyTV** [comment]
Sorry, can't reproduce your issue. With a server called `waiting` set another server `server` all of these work:
- being on `server` while maintenance is activated -> kicked to `waiting`
- already on `waiting` -> nothing happens
- not on the network (previously on any server, does not matter which) -> sent to `waiting` on join

I will reopen this if you can reproduce it on a clean proxy with minimal setup and clear steps to reproduce the issue
