### ISSUE TITLE
Check for bypass permission removal

### ISSUE THREAD

**Issue by Magi1053** [KennyTV/Maintenance#49]
Even though the config option for `kick-online-players: true`, if a player online has their maintenance.bypass permission removed, they do not get kicked from the server.

**Comment by KennyTV** [comment]
I simply do a permission check via Bukkit API - your permission plugin will have to handle the refreshing itself

**Comment by Magi1053** [comment]
You only check when the user joins though right, there are no recurring checks to see if the user still has permissions

**Comment by KennyTV** [comment]
Why would I? 👀 The kick is only applied once: When maintenance is initially enabled with online players (and then of course blocking new connections). Doing a check every x seconds sounds rather out of scope here and is better done by using API of Maintenance and the permission plugin itself
