### ISSUE TITLE
%NEWLINE% not working

### ISSUE THREAD

**Issue by Gerbildral** [KennyTV/Maintenance#50]
hello,

i have installed the plugin on my bungeecord server and i changed nothing to the config but the %NEWLINE% doesnt work.
![image](https://user-images.githubusercontent.com/29066252/93026797-f9d6da00-f608-11ea-83d7-c8ba9ac5ddd8.png)

is this a bugg or did i miss anything?

**Comment by Gerbildral** [comment]
![image](https://user-images.githubusercontent.com/29066252/93026818-1b37c600-f609-11ea-9c08-04618337d50d.png)

this is a better image

**Comment by KennyTV** [comment]
Yep, you can download 3.0.6 with the fix here: https://github.com/KennyTV/Maintenance/suites/1095763596/artifacts/15239836

**Comment by Gerbildral** [comment]
thanks for the fast response!
