### ISSUE TITLE
Exception while loading plugin on startup

### ISSUE THREAD

**Issue by MrTalon63** [KennyTV/Maintenance#51]
## Bug reproducibility
Put plugin jar into bungees plugin folder, start the server

## Error
https://hastebin.com/izewenajis.css

## Server information
Can't get

**Comment by KennyTV** [comment]
Sounds like you either have a broken jar or set an invalid language in the config

**Comment by MrTalon63** [comment]
I forgot to rename the messages file to language-pl.yml, dumb fix for dumb issue.
