### ISSUE TITLE
[Suggestion] Add Maintenance Duration Placeholder

### ISSUE THREAD

**Issue by adenosine1** [KennyTV/Maintenance#58]
Add a Maintenance Duration placeholder and language options when using the scheduletimer command. I would like to have the option for broadcasts to say how long the maintenance will last when using the scheduletimer command. 

Something like:
"Maintenance will be activated in <Time> and will last <Duration>

**Comment by KennyTV** [comment]
Thank you for the suggestion, `scheduletimerBroadcast` and `singleScheduletimerBroadcast` have been added to the language files in the dev branch.
