### ISSUE TITLE
[Suggestion] Add Hex Color Support for 1.16+ Servers

### ISSUE THREAD

**Issue by Myzumi** [kennytv/Maintenance#59]
Please add Hex Color support for Servers above 1.16

**Comment by KennyTV** [comment]
In theory you can already use Bungee Chat's rgb hack (like `§x§a§a§b§b§c§c`), but I'm hoping on using a better chat component library in the future - that requires a bit of work and would likely make this plugin Spigot/Bungee incompatible in favor of Paper/Waterfall (Velocity and Sponge already bundle that lib)

**Comment by F1b3rDEV** [comment]
https://github.com/F1b3rDEV/minecraft-spigot-rgb-chat-support ^^

**Comment by kennytv** [comment]
Adventure component support with MiniMessage parsing has been added and will at some point be released, the initial wip can be found here https://github.com/kennytv/Maintenance/actions/runs/1631269460 (in case anyone uses them, make backups of your old configuration to use when 4.0.0 is actually released, otherwise you will miss out on new automatic upgrades from now)
And here's a MiniMessage webeditor https://webui.adventure.kyori.net/

**Comment by JosGCS** [comment]
> Adventure component support with MiniMessage parsing has been added and will at some point be released, the initial wip can be found here https://github.com/kennytv/Maintenance/actions/runs/1631269460 (in case anyone uses them, make backups of your old configuration to use when 4.0.0 is actually released, otherwise you will miss out on new automatic upgrades from now) And here's a MiniMessage webeditor https://webui.adventure.kyori.net/

That's not the type of HEX Color Support we're trying to request, take a look at [ServerListPlus](https://github.com/Minecrell/ServerListPlus) plugin HEX Color System: [https://i.imgur.com/GWcxiPr.png](https://i.imgur.com/GWcxiPr.png)

**Comment by kennytv** [comment]
MiniMessage probably has better and more streamlined rgb support with gradients and whatnot than any other plugin; take a look at https://docs.adventure.kyori.net/minimessage#usage and test with the linked webui

**Comment by JosGCS** [comment]
> MiniMessage probably has better and more streamlined rgb support with gradients and whatnot than any other library; take a look at https://docs.adventure.kyori.net/minimessage#usage and test with the linked webui

Gradient works fine at 1.16+ servers, but users using Minecraft 1.7.x see this: [https://i.imgur.com/FlDBdiH.png](https://i.imgur.com/FlDBdiH.png)

**Comment by kennytv** [comment]
RGB colored components are a recent addition, whatever happens for lower versions you'll just have to accept and is not supported
