### ISSUE TITLE
MySQL not working

### ISSUE THREAD

**Issue by MastoryMd5** [KennyTV/Maintenance#61]
## Bug reproducibility
Cannot use MySQL functionality, when i enable mysql i get the error.

## Error
https://dpaste.org/v5PX

## Server information
Can't paste maintenance dump since gives error 500
Using velocity 1.1.5 and maintenance 3.0.6
Mariadb version 10.3.27

**Comment by KennyTV** [comment]
Ah I thought I would never see the day someone actually tried it on Velocity. Fixed in dev builds, you can find it under the latest action https://github.com/KennyTV/Maintenance/actions if finished
