### ISSUE TITLE
After downloading Protocollib MOTD doesnt work

### ISSUE THREAD

**Issue by andreighigea** [kennytv/Maintenance#81]
## Bug reproducibility
I installed both Maintenance and Protocollib and the MOTD from maitenence stoped working it just shows me the default MOTD. The only other plugin i have is essentialsX.

## Error
no error just the problem

## Server information
https://hastebin.com/inesuwifex

**Comment by CodeByCam** [comment]
Hey there!
Thanks for creating an issue, we hope to get Maintenance working for you again ASAP!!!

Could you try Maintenance again without using ServerListPlus? ServerListPlus doesn't seem to be actively maintained, there are much better, modern, and well made server list plugins like [MiniMOTD](https://github.com/jpenilla/MiniMOTD/) that you can use.
