### ISSUE TITLE
Player added to whitelist, can't join

### ISSUE THREAD

**Issue by rageyh** [kennytv/Maintenance#89]
1. Active maintenance
2. add a player to whitelist maintenance
3. join

https://prnt.sc/Yw24XVWhnnrU

https://hastebin.com/sinolujode

**Comment by pedro-dalben** [comment]
here too..

**Comment by wrexik** [comment]
Hey, same here!

**Comment by Link0Darck** [comment]
if the server is cracked you must deactivate the whitelist it connects then add to the list and reactivate

**Comment by kennytv** [comment]
There's now an option to fall back to offline mode uuids, but generally speaking, I don't offer full support for cracked servers
